app = "meeting-backend-CHANGE_ME"
primary_region = "ams"

[build]
  dockerfile = "./Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "4000"
  DATABASE_URL = "sqlite:/app/data/prod.sqlite"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  source = "data"
  destination = "/app/data"

