services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=development
      - PORT=4000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET:-change-me}
      - DATABASE_URL=sqlite:/app/data/dev.sqlite
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - backend_data:/app/data
  frontend:
    build: ./frontend
    environment:
      - PORT=3000
      - REACT_APP_API_URL=http://localhost:4000
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./frontend:/app
volumes:
  backend_data:
