services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=development
      - PORT=4000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
  frontend:
    build: ./frontend
    environment:
      - PORT=3000
      - REACT_APP_API_URL=http://localhost:4000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
