services:
  - type: web
    name: meeting-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm ci
    startCommand: node src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:/app/data/prod.sqlite
    healthCheckPath: /health
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1

staticSites:
  - name: meeting-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://<your-backend-hostname>
