apiVersion: v1
kind: Namespace
metadata:
  name: meeting
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: meeting
type: Opaque
stringData:
  OPENAI_API_KEY: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: meeting
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting-backend
  namespace: meeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meeting-backend
  template:
    metadata:
      labels:
        app: meeting-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/your-org/meeting-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4000"
            - name: DATABASE_URL
              value: "sqlite:/app/data/prod.sqlite"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: OPENAI_API_KEY
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: backend-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: meeting-backend
  namespace: meeting
spec:
  selector:
    app: meeting-backend
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: http

